### ISSUE TITLE
All Queries shown as executed from Builder

### ISSUE THREAD

**Issue by percymamedy** [fitztrev/query-tracer#1]
All my queries are being shown as being executed from 

```
"vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php" and "query.line" <> "1124"
```

**Comment by fitztrev** [comment]
What is your environment?

**Comment by sarfraznawaz2005** [comment]
I dont see any query trace info showing up. Using clockwork with lv 5.1.

**Comment by fitztrev** [comment]
@sarfraznawaz2005 it requires the global scopes that were released in 5.2

**Comment by fitztrev** [comment]
@percymamedy when the package does its backtrace, it looks for the first file path that does not include "/vendor/". If you're on Windows, the directory separators may be different.

**Comment by percymamedy** [comment]
@fitztrev I am using xampp on windows yes.
