### ISSUE TITLE
Already in Debugbar

### ISSUE THREAD

**Issue by barryvdh** [fitztrev/query-tracer#4]
Did you know that Debugbar can already trace queries? Just set `debugbar.options.db.backtrace` to `true`.

See this code: https://github.com/barryvdh/laravel-debugbar/blob/97e8f6095f650b9c5f22a11ad8adf9000987f624/src/DataCollector/QueryCollector.php#L199-L225

![image](https://cloud.githubusercontent.com/assets/973269/15324633/89b68a3a-1c47-11e6-90f2-326246ab3370.png)

It adds them to the right.

**Comment by fitztrev** [comment]
Hi @barryvdh,

I didn't until someone pointed it out. Great package, and yes, that would be better than my implementation if someone is using Debugbar.
