### ISSUE TITLE
Interface 'Illuminate\Database\Eloquent\Scope' not found

### ISSUE THREAD

**Issue by vedovelli** [fitztrev/query-tracer#5]
Please see:

![screen shot 2016-05-17 at 2 06 22 pm](https://cloud.githubusercontent.com/assets/151001/15331645/a77befe2-1c38-11e6-803f-c441bed9fb22.png)

Thanks in advance!

**Comment by fitztrev** [comment]
What version of Laravel are you using? This package makes use of the updated global query scopes in 5.2.

**Comment by vedovelli** [comment]
I'm using 5.1.

So we know what the problem is!

Thanks for the reply!

**Comment by aBusyAnt** [comment]
Class name have to be the same as Filename

**Comment by wadleo** [comment]
thanks @GrayLuo
